In [1]:
#cat seems to expand the dimension while stack more like packaging two relative things
import numpy as np

a = np.arange(6).reshape(1,2,3)
b = np.array([[[7,8,9],[10,11,12]]])
print(a)
print(b)

[[[0 1 2]
  [3 4 5]]]
[[[ 7  8  9]
  [10 11 12]]]


In [2]:
print(np.concatenate((a,b)))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 7  8  9]
  [10 11 12]]]


In [3]:
print(np.concatenate((a,b),axis=0))
print('\n')
print(np.concatenate((a,b),axis=1))
print('\n')
print(np.concatenate((a,b),axis=2))

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 7  8  9]
  [10 11 12]]]


[[[ 0  1  2]
  [ 3  4  5]
  [ 7  8  9]
  [10 11 12]]]


[[[ 0  1  2  7  8  9]
  [ 3  4  5 10 11 12]]]


In [4]:
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[7,8,9],[10,11,12]])
print(c)
print('\n')
print(d)

[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]


In [5]:
print(np.stack((c,d),0))
print('\n')
print(np.stack((c,d),1))

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [6]:
print(np.hstack((c,d)))
print('\n')
print(np.vstack((c,d)))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
