In [1]:
import numpy as np

a = np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
print(np.append(a,[10,11,12]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
print(np.append(a,[[10,11,12,13,14]],axis = 0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [8]:
print(np.append(a,[[5,6,7],[10,11,12]],axis = 1))

[[ 0  1  2  3  4  5  6  7]
 [ 5  6  7  8  9 10 11 12]]


In [9]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
print(np.insert(a,1,[8,9]))

[1 8 9 2 3 4 5 6]


In [11]:
print(np.insert(a,1,[8,9],axis=0))

[[1 2]
 [8 9]
 [3 4]
 [5 6]]


In [14]:
print(np.insert(a,1,[8,9,10],axis=1))

[[ 1  8  2]
 [ 3  9  4]
 [ 5 10  6]]


In [18]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
print(np.delete(a,6))

[ 0  1  2  3  4  5  7  8  9 10 11]


In [21]:
print(np.delete(a,2,axis=0))

[[0 1 2 3]
 [4 5 6 7]]


In [22]:
print(np.delete(a,2,axis=1))

[[ 0  1  3]
 [ 4  5  7]
 [ 8  9 11]]
